#!/bin/bash

# Get list of names from already existing folders in Downloads/Archive
# path: core path
# ext: extensional path

path=/mnt/disk-
ext=(
	Archive/porn/vids
	Archive/porn/pics
	Downloads/porn
)

for d in {d..j}; do
	for e in "${ext[@]}"; do
		ls $path$d/$e >> list.txt
	done
done
