#!/bin/bash

# path to files currently sitting at completed downloads
files=(/mnt/disk-j/lin_downs/*) # TODO: change to lin_downs_c after testing
# lowercase the file list
files_lower=()
for file in "${files[@]}"; do
	declare -l file
	file=$file
	files_lower+=($file)
done

# array of the list read from filtered_list.txt
mapfile -t list < filtered_list.txt

# loop through 
for file in "${files_lower[@]}"; do
	for reg in "${list[@]}"; do
		if [[ $file =~ $reg ]]; then
			echo "---"
			echo $file
			echo $reg
			echo "---"
		fi
	done
done
