#!/usr/bin/env python3

# recreation of move_files in python
import os
import re

DWN_DIR = os.path.join('/mnt', 'disk-j', 'lin_downs')
LIST_FILE = 'filtered_list.txt'


with open(LIST_FILE) as f:
	tags = f.read().splitlines()

downloads = os.listdir(DWN_DIR)

for el in tags:
	for down in downloads:
		full_path = os.path.join(DWN_DIR, down)
		m = re.search(el, down.lower())
		if (m):
			if os.path.isdir(full_path):
				print('DIR')
			elif os.path.isfile(full_path):
				print('FILE')
			else:
				print('ELSE')
			print(el)
			print(down)
			print('---')
