#!/usr/bin/env python3

# recreation of move_files in python
import os
import re
import shutil
import time
import sys

DWN_DIR = os.path.join('/mnt', 'disk-j', 'lin_downs_c')
ARCH_DIR = os.path.join('/mnt', 'disk-j', 'arch')
DEST_DIR = os.path.join(ARCH_DIR, 'porn')
LOG = os.path.join(ARCH_DIR, 'log')
LIST_FILE = os.path.join(os.path.expanduser('~'), 'git', 'downloads-categoriser', 'filtered_list.txt')


with open(LIST_FILE) as f:
	tags = f.read().splitlines()
downloads = os.listdir(DWN_DIR)
total_time = 0
num_of_mv = 0
start = time.time()

for tag in tags:
	match = list(filter(re.compile(tag, re.IGNORECASE).search, downloads))
	if len(match) > 0:
		for down in match:
			num_of_mv += 1
			full_path = os.path.join(DWN_DIR, down)
			if os.path.isdir(full_path):
				dir_or_file = 'DIR'
			elif os.path.isfile(full_path):
				dir_or_file = 'FILE'
			else:
				dir_or_file = 'ELSE??'
			print('moving %s: %s.' % (dir_or_file, down))
			try:
				# turn regex back to normal directory names
				tag = tag.replace('[\. _-]*', '_')
				os.makedirs(os.path.join(DEST_DIR, tag), exist_ok=True)
				shutil.move(full_path, os.path.join(DEST_DIR, tag, down))
			except Exception as e:
				print(e)

if num_of_mv == 0:
	print('nothing moved. exiting.')
	sys.exit()

end = time.time()
passed = end - start
total_time += passed
stat = '%s: moving %d objects took %.2f seconds.\n' % (time.strftime('%Y-%m-%d %H:%M:%S'), num_of_mv, total_time)
with open(LOG, 'a') as l:
	l.write(stat)
